# Generated by Django 5.0 on 2024-01-16 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelForm',
            new_name='django_model',
        ),
    ]
